### ISSUE TITLE
super dumb bug 

### ISSUE THREAD

**Issue by Diegopyl1209** [Quickdesh/Animiru#14]
### Steps to reproduce

1. Open the app
2. Go to any anime
3. Wait to load episodes 
4. Long press in any episode
5. Long press in filler option or Mark option

### Expected behavior

Just appear the description of the selected option

### Actual behavior

Appear the description of filler and Mark option 

### Animiru version

0.13.3.3

### Android version

Android 11

### Device

Nokia 13072

### Other details

https://user-images.githubusercontent.com/80992641/182081214-42773aa8-8525-4d51-872b-0a0a804e98a8.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3.3](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Oop, thank you for pointing it out. I'll fix it in the next update

**Comment by Quickdesh** [comment]
fixed in commit [`6eae3a1`](https://github.com/Quickdesh/Animiru/commit/6eae3a1cbdecbc3f9ea5f9c1eadfa77ac9369e07)
