### ISSUE TITLE
Global search still showing up on manga links

### ISSUE THREAD

**Issue by Patriarch9307** [Quickdesh/Animiru#15]
### Steps to reproduce

1. tap to open a manga link
2. android app selection will offer animiru

### Expected behavior

Only tachiyomi or related apps should show up

### Actual behavior

Animiru, which doesn't have manga capabilities show up.

### Animiru version

0.13.3.3

### Android version

Android 12

### Device

Tecno Spark 6 (with custom aosp rom)

### Other details

![Screenshot](https://user-images.githubusercontent.com/108529338/182152489-1e13a95b-eefb-4f01-bcad-b023ca296674.png)

I reported it in #12 but the bug still exists.

I also cleared app data and even reinstalled the app but this still occurs.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.3.3](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Fack. I have it fixed, forgot to upload it in this release. So sorry. I'll publish a new release with the fix within the next 6 hours.

Sorry again and thank you for your patience!

**Comment by Quickdesh** [comment]
Closed in commit https://github.com/Quickdesh/Animiru/commit/7d38b1159f07beecdc897c10f01285d90d37b82e
