### ISSUE TITLE
Vídeo Quality

### ISSUE THREAD

**Issue by MFMelloReal** [Quickdesh/Animiru#16]
### Describe your suggested feature

The option to set a standard quality to videos and downloads would be life-saving. It's really dumb to download a video and only be able to watch It in the lowest quality possible as well to change the vídeo quality EVERY. SINGLE. TIME. you enter in it.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.3.4](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
See browse, anime extentions and select the settings of extensions. You can change the prefered quality there

**Comment by MFMelloReal** [comment]
> See browse, anime extentions and select the settings of extensions. You can change the prefered quality there

Haven't seen It LMAO 

Thx man!
