### ISSUE TITLE
Local Anime Source infinite loading of episode

### ISSUE THREAD

**Issue by Patriarch9307** [Quickdesh/Animiru#18]
### Steps to reproduce

1. Have a local anime source as  Animiru/local/[Anime name]/[episodes]
2. Go to browse > local anime source > select a anime
           2.1. or simply have a library entry from local anime source
3. play an episode

### Expected behavior

Episode should play

### Actual behavior

infinite loading animation and episode doesn't play no matter how long I wait

### Crash logs

Animiru verbose crash log, might help
[aniyomi_crash_logs.txt](https://github.com/Quickdesh/Animiru/files/9382470/aniyomi_crash_logs.txt)

### Animiru version

0.13.4.1

### Android version

Android 12

### Device

Tecno Spark 6 (with custom aosp rom)

### Other details

So in order to isolate the problem, I tested the previous version 0.13.3.6 and this problem isn't present there.
I also tested aniyomi-mpv-beta r5235 to see if this issue was present upstream, but that works perfectly fine. 

I should also mention, if I try to open that episode in external player (vlc) from the app, it gives a toast notification saying:
     "Collection contains no element matching the predicate."

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4.1](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Sorry that it took a while

**Comment by Quickdesh** [comment]
fixed in https://github.com/Quickdesh/Animiru/commit/ecfca16aabe123029632e40d524b7588a8624a23
