### ISSUE TITLE
drop "anime" prefix from different strings

### ISSUE THREAD

**Issue by Patriarch9307** [Quickdesh/Animiru#21]
### Describe your suggested feature

Remove the anime prefix from various strings across the ui like "anime sources" or "anime extensions" or "local anime source"

### Other details

This prefix comes from aniyomi where it makes sense as it needs to differentiate between anime and manga side of the app.
But animiru only supports anime, having this prefix specifying the type is not really needed.
Removing it will also make the browse UI look less bloated on smaller devices.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4.4](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Good idea, will do

**Comment by Quickdesh** [comment]
Fill be added in next release

**Comment by quickdesh** [comment]
Dropped in as many as possible while keeping compatibility with other strings
