### ISSUE TITLE
[F-R] Release Flavor Without Connections Function

### ISSUE THREAD

**Issue by RickyM7** [Quickdesh/Animiru#22]
### Describe your suggested feature

This function makes the app a few times heavier, but it's not used for many people (I think), so please make a flavor without this.

Note: This is a really nice function, of couse, but ins't userful for people that don't use discord or just want watch your animes sometimes.

Note 2: Sorry for my bad English, it's not my first language.

Anyway, thank you so much for this awesome project.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4.4](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
The Connections tab is one of the main defining features of Animiru so I am not going to create a flavour without it

It actually barely affected the size, the majority of the change was due to internal ui changes with the code.

The next update will fix that issue and it will become smaller again

**Comment by RickyM7** [comment]
> The Connections tab is one of the main defining features of Animiru so I am not going to create a flavour without it
> 
> It actually barely affected the size, the majority of the change was due to internal ui changes with the code.
> 
> The next update will fix that issue and it will become smaller again

Ok, thank you so much!
