### ISSUE TITLE
Browse tabs not aligned properly 

### ISSUE THREAD

**Issue by Patriarch9307** [Quickdesh/Animiru#25]
### Steps to reproduce

Have a larger screen or increase the DPI in system settings

Go to browse

### Expected behavior

The tabs should be aligned to the centre 

### Actual behavior

They are aligned to the left
![Screenshot_Animiru](https://user-images.githubusercontent.com/108529338/210125490-b38606a7-925f-4650-b585-f2f41de1f466.png)

### Animiru version

0.13.4.4

### Android version

Android 13

### Device

Tecno spark 6

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.13.4.4](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
should be fixed next update

**Comment by quickdesh** [comment]
I did something better, i removed the tabs altogether
