### ISSUE TITLE
[F-R] Use Aniyomi's Translations

### ISSUE THREAD

**Issue by RickyM7** [Quickdesh/Animiru#29]
### Describe your suggested feature

It would be great if the project used Aniyomi's Weblate translations. Maybe embed the project into tachiyomi and aniyomi's weblate to share the same translations of shared components. This would be extremely helpful as the app is currently not translated.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4.4](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Quickdesh** [comment]
Ye, I have the code ready

I had just temporarily disabled it for other uses

Will bring it back by the next update

**Comment by quickdesh** [comment]
Has been added. There are quite a few translations that are animiru specific though
