### ISSUE TITLE
Stable Update

### ISSUE THREAD

**Issue by ghost** [Quickdesh/Animiru#31]
### Describe your suggested feature

when new version of animiru is going to release.
there are few issues like lagging when scrolling extension sources page and anime with huge episode page .app crashing when we change in player video codec to sw from  hw÷
i hope  new update will be released soon

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4.4](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by quickdesh** [comment]
Soon ;)
