### ISSUE TITLE
[F-R] Division between Languages ​​in the Font List

### ISSUE THREAD

**Issue by RickyM7** [Quickdesh/Animiru#34]
### Describe your suggested feature

The new font list style doesn't show what language the font is in the download part, which can be a little confusing for people who use multiple language fonts.  The ideal would be to have a divider with the name of the language as it is on the main page of the Explore tab.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.1.5](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by quickdesh** [comment]
Same as #36 ( will fix from there )
