### ISSUE TITLE
Animiru for Android tv 

### ISSUE THREAD

**Issue by Kratos10002** [Quickdesh/Animiru#35]
### Describe your suggested feature

I love the app and would be great for Android tv. Thanks 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.1.5](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by quickdesh** [comment]
Same as #19
