### ISSUE TITLE
"installed" in the extension install screen

### ISSUE THREAD

**Issue by Patriarch9307** [Quickdesh/Animiru#36]
### Steps to reproduce

Open browse > extension install 

### Expected behavior

There is no "installed" label for available extensions 

### Actual behavior

There is "installed" label for available extensions 

### Animiru version

0.14.1.5

### Android version

Android 13

### Device

N/A

### Other details

![Screenshot_20230405-085314_Animiru_1](https://user-images.githubusercontent.com/108529338/229977948-56bdd3a7-27c3-48c5-a656-3c873bb96365.png)

I might be missing something here but the installed label doesn't seem to make sense. Maybe it is for available updates?
It should be hidden for not installed extensions.

Anyway loved the new update, thanks for working on this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1.5](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by quickdesh** [comment]
Ah shit, i think I messed up a boolean check and its showing only installed. It shouldnt be showing installed. Thanks for the issue
