### ISSUE TITLE
Crash on "cleanup download"

### ISSUE THREAD

**Issue by Patriarch9307** [Quickdesh/Animiru#37]
### Steps to reproduce

Go to advanced settings
Tap "Clean up downloaded episodes"
Select everything and tap "ok"

### Expected behavior

Do what it is supposed to do

### Actual behavior

Crash

### Crash logs

![Screenshot_20230405-091701_Animiru_1](https://user-images.githubusercontent.com/108529338/229980190-49438ed1-9f3e-42f3-84ad-bccd3c99d425.png)
![Screenshot_20230405-091706_Animiru_1](https://user-images.githubusercontent.com/108529338/229980198-fcd8fb2f-dedd-44ee-9052-1396b4fe4a4e.png)

Crash log seems to be empty:
[animiru_crash_logs.txt](https://github.com/Quickdesh/Animiru/files/11155155/animiru_crash_logs.txt)

### Animiru version

0.14.1.5

### Android version

Android 13

### Device

Tecno spark 6

### Other details

Dumped crash log being empty might be another issue to look into

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.1.5](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by quickdesh** [comment]
oof, thank you so much for pointing out all the problems mate!
