### ISSUE TITLE
Continue watching label

### ISSUE THREAD

**Issue by Patriarch9307** [Quickdesh/Animiru#44]
### Steps to reproduce

Filter > display 

### Expected behavior

Continue watching button 

### Actual behavior

Continue watching/reading button 

### Animiru version

0.14.2.0

### Android version

Android 13

### Device

N/A

### Other details

![Screenshot_20230409-095719_Animiru](https://user-images.githubusercontent.com/108529338/230755310-c21c4c25-e667-4f21-9b6a-cc1c02da5484.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2.0](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Patriarch9307** [comment]
This issue still persists

**Comment by quickdesh** [comment]
Oof, I thought i fixed it, will fix in new release
