### ISSUE TITLE
Video rotation

### ISSUE THREAD

**Issue by Halow61** [Quickdesh/Animiru#46]
### Steps to reproduce

1.First Step - Download 9anime(extension).
2.Second Step - Open the extension.
3.Third Step - Select any anime.
4.Fourth Step - Once you select an anime, press the "WebView" button.

THE ISSUE HERE IS, YOU CAN'T ROTATE THE VIDEO ON THE "WEBVIEW SITE". To put it simply, you can't rotate the video in the WebView, not in the Animiru app itself.

### Expected behavior

This should happen, once I press the WebView and press the rotate button on that site. It should be able to rotate my whole device and be on full screen.

### Actual behavior

This happened when I was doing my beating my thing in R34(extension). I was so excited to let it out BUT THE VIDEO WAS TAKING TOO LONG TO LOAD, I spammed the full screen button or rotate button but it isn't working. That's the whole thing.

### Animiru version

0.14.2.0

### Android version

Android 12 5G

### Device

Redmi Note 10

### Other details

PLEASE ALSO FIX THE LOADING. I HAVE A PLDT WIFI with 65MBPS, it runs fast in EVERY APP but in animiru. IT'S JUST TAKING TOO LONG!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.2.0](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by quickdesh** [comment]
Webview rotation was and will never be added since ti only exists to bypass captchas and such
