### ISSUE TITLE
Support for Android Tv

### ISSUE THREAD

**Issue by ahmedziyaanmuhamed** [Quickdesh/Animiru#48]
### Describe your suggested feature

Currently animiru or aniyomi doesn't fully work in Android Tv with a remote.
So can add support for Android Tv remote 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.14.2.0](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by GMRobo** [comment]
Please see #19
