### ISSUE TITLE
Library gets reset by itself.

### ISSUE THREAD

**Issue by kyoyacchi** [Quickdesh/Animiru#53]
### Steps to reproduce

1. Try to watch an anime episode (for ex, i used turkanime)
2. Finish the anime episode.
3. Exit from episode.
4. App locks itself then makes me force close it then resets all the anime in the library.

or, 
1. Try to watch an episode.
2. Lock the device (while in player)
3. Unlock it.
4. Same result.

_I also explained this bug in discord, #bug-reports channel._ 

https://discord.com/channels/1009125884491468861/1009128186774302761/1130597940637999184

### Expected behavior

It shouldn't lock and reset my library.

### Actual behavior

It locks the app the apps then shows the loading indicator, closing and re opening it resets my library. 

https://cdn.discordapp.com/attachments/746414614316843152/1132992112103788574/screen-20230724-140529.mp4

### Crash logs

https://cdn.discordapp.com/attachments/1009128186774302761/1130597939648139375/animiru_crash_logs.txt

https://cdn.discordapp.com/attachments/871133764410019890/1170658290661863504/animiru_crash_logs.txt

### Animiru version

0.14.3.0

### Android version

Android 11

### Device

Tecno Spark 7T

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.14.3.0](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by quickdesh** [comment]
Shouldnt happen from new update

**Comment by kyoyacchi** [comment]
Yeah, it's not happening anymore. Thanks!!

**Comment by kyoyacchi** [comment]
It still occurs @Quickdesh

**Comment by kyoyacchi** [comment]
It seems that this occurs when i change the sorting to anything else than "⬆️ alphabetically"

**Comment by kyoyacchi** [comment]
It's gone, i guess. I haven't had this since he latest update. I'll reopen the issue if it happens again.
