### ISSUE TITLE
[Feedback] Next Episode Countdown

### ISSUE THREAD

**Issue by Patriarch9307** [Quickdesh/Animiru#56]
### Describe your suggested feature

Overall it is a nice feature, but here are some thing I have noticed that I would like to give feedback on:

- Ability to turn it off 😅

- It should be less like the actual episode holder, meaning currently apart from colour, there is not clear distinction between them. It being a sup-text to the episode count would be nice in my opinion.

- Maybe round it off? having a counter becomes meaningless when the delay is more than a day. `04d 00h 50m 02s` is too excessive, it should just be rounded off to like `next episode airs in 4 days`, `next episode airs in 17 hours` etc

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.0.0](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by quickdesh** [comment]
Ability to turn it off is one thing I plan to add, as for the design, that will stay. It's been tested within aniyomi and was the best option to go with for majority of the users

**Comment by quickdesh** [comment]
Option to turn it off has been added
