### ISSUE TITLE
Default playback speed

### ISSUE THREAD

**Issue by MF-Debug** [Quickdesh/Animiru#57]
### Describe your suggested feature

An option to set the playback speed to a specific value by default whenever I play something would be great.

### Other details

For example, I always use the x1.25 option to play. When I start playing something, I have to manually adjust it every time which is a bit annoying for me.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by quickdesh** [comment]
It auto chooses the last option when exiting the player now
