### ISSUE TITLE
BRING BACK HIDE OPTION FOR NAVIGATION AND HISTORY 

### ISSUE THREAD

**Issue by RUDRAKSH-7** [Quickdesh/Animiru#58]
### Describe your suggested feature

This feature just got removed in the latest version. BRING IT BACK cz it makes the Nav pill looks good

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by quickdesh** [comment]
Have introduced Recents Tab to minimize the amount of tabs. Will keep improving the Tab system from here on out

**Comment by RuDru-OP** [comment]
> Have introduced Recents Tab to minimize the amount of tabs. Will keep improving the Tab system from here on out
when is the next update coming bro?
Its been a while...

**Comment by RUDRAKSH-7** [comment]
When is the next update coming?
its been a while

**Comment by quickdesh** [comment]
In an hour or so

**Comment by RUDRAKSH-7** [comment]
wohoooo
