### ISSUE TITLE
Number of extensions that need an update is cut off on the nav bar

### ISSUE THREAD

**Issue by MF-Debug** [Quickdesh/Animiru#62]
### Steps to reproduce

Check an extension that needs an update

### Expected behavior

The number shouldn't be cut off on the nav bar when it is selected and highlighted.

### Actual behavior

The number is slightly cut off
![Screenshot_20230922-015118_Animiru](https://github.com/Quickdesh/Animiru/assets/6173607/ee8241b1-9c1b-4a0b-bf1a-c933193b6878)

### Animiru version

0.15.2.3

### Android version

Official LOS 18.1

### Device

Samsung Galaxy Note 3 SM-N9005

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/help/faq/) and [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by quickdesh** [comment]
Fixed in new update!
