### ISSUE TITLE
Allow blacklisting hosts for default download/playback source

### ISSUE THREAD

**Issue by nididak** [Quickdesh/Animiru#63]
### Describe your suggested feature

Sometimes certain hosts are unavailable (Eg. vidcloud on aniwave, formerly 9anime) which is not an issue on it's own but when that host is default selection bulk download simply doesn't work and requires user to download from another host, 1 by 1.

### Other details

While some site extensions indeed allow disabling/enabling hosts, it's not always up-to-date and/or available. Users should be able to block problematic hosts on their own. I think a regex would be simple enough for many.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
That kind of contradicts the extension settings. I don't see a benefit in that. 🤔

**Comment by nididak** [comment]
> That kind of contradicts the extension settings. I don't see a benefit in that. 🤔

fair enough, closing
