### ISSUE TITLE
Ability to turn on subtitles

### ISSUE THREAD

**Issue by ghost** [Quickdesh/Animiru#65]
### Describe your suggested feature

The sites have both dubbing and subtitles. But Animiru doesn't turn on subtitles, so we can only watch dubbed and unsubtitled. It would be very helpful to have a subtitle activation feature. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by LittleFreak** [comment]
Currently, the (soft)subs are only shown during foreign text, when dubs are also present (see yomiroll,...)
> ### Describe your suggested feature
> The sites have both dubbing and subtitles. But Animiru doesn't turn on subtitles, so we can only watch dubbed and unsubtitled. It would be very helpful to have a subtitle activation feature.

You mean, like seeing the subtitle nonstop, while the dub is running?

**Comment by quickdesh** [comment]
This is usually due to extensions not providing said data for the specific video in question
