### ISSUE TITLE
Episodes are not marked as watched when using external player

### ISSUE THREAD

**Issue by pjueon** [Quickdesh/Animiru#70]
### Steps to reproduce

- Enable "always use external player" option
- Set "External player preference" to VLC
- Watch anime with external player (VLC)

### Expected behavior

Episodes are marked as watched after watching.

### Actual behavior

- Episode is not marked as watched. 
- "Preserve watch position on seen episodes" option also doesn't work

### Animiru version

0.15.2.3

### Android version

Android 13

### Device

Windows 11(using WSA)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/help/faq/) and [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.2.3](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by quickdesh** [comment]
Should be fixed in new update!
