### ISSUE TITLE
Increase the height of Navigation Bar

### ISSUE THREAD

**Issue by NikunjK8** [Quickdesh/Animiru#73]
### Describe your suggested feature

If possible, please increase the height of Navigation Bar. Now the pill is gone which i used to like, the app is harder to navigate. I compared it with Aniyomi and the navigation bar of this app is almost half the height of Aniyomi. It's look good but it's not very practical.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0.0](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by lasersPew** [comment]
I am against the actions this issue proposes tho it would be good if this becomes a setting.

**Comment by NikunjK8** [comment]
That would work too. The size Aniyomi uses is universal and used among most of the android applications. Because it works fine with any thumb size and placements.

**Comment by quickdesh** [comment]
I have increased the height to match the standardised version

**Comment by NikunjK8** [comment]
Thanks a lot
