### ISSUE TITLE
TABS REMOVAL OPTION

### ISSUE THREAD

**Issue by RUDRAKSH-7** [Quickdesh/Animiru#77]
### Describe your suggested feature

please give the option to remove updates tab and history tab completely from home. I just want a minimal look and ease of access for the app. Overall App kind lookin Good

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0.0](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by lasersPew** [comment]
Looks like #82.

**Comment by RUDRAKSH-7** [comment]
are you Fugging stupid. that is literally something else (for category options and so) And this is about something that was there earlier but had been removed in the recent updates

**Comment by kyoyacchi** [comment]
> are you Fugging stupid. that is literally something else (for category options and so) And this is about something that was there earlier but had been removed in the recent updates

Calm down bud

**Comment by LittleFreak** [comment]
> are you Fugging stupid. that is literally something else (for category options and so) And this is about something that was there earlier but had been removed in the recent updates

~~Well... Maybe we are, but~~ we also think ahead and can imagine, how both topics could be related, since a tab removal option is appearance related like in the mentioned issue above.

**Comment by RUDRAKSH-7** [comment]
Oh then my bad... He should have mentioned that the photos provided look like the requested feature. What I thought was that he is gonna close this issue saying that the issue is already present. (cz this has happened to me before in aniyomi's repository)

**Comment by LittleFreak** [comment]
Neither he nor I can close them, because we're not part of the repo moderators.
But we still feel free to mention similar or identical issues 😉

**Comment by quickdesh** [comment]
I have introduced a new Recents page instead. Will be slowly improving this page and shifting away the more screen to keep 3-4 tabs in the bar at all times
