### ISSUE TITLE
Flaw in filler filter

### ISSUE THREAD

**Issue by LittleFreak** [Quickdesh/Animiru#79]
### Steps to reproduce

1) Mark an episode of an anime as filler
2) Try to hide all filler episodes with the filter function

### Expected behavior

All filler marked episodes will be hidden

### Actual behavior

All filler marked episodes are still shown 😞

### Animiru version

0.16.0.0

### Android version

Android version: 14 (SDK 34; build UP1A.231005.007.X806BXXU5CWK7) Android build ID: UP1A.231005.007.X806BXXU5CWK7 Device brand: samsung Device manufacturer: samsung Device name: gts8p (gts8pxeea) Device model: SM-X806B WebView: Android System WebView 120.0.6099.193

### Device

Galaxy Tab S8+

### Other details

![Screenshot_20240204_165836_Animiru](https://github.com/Quickdesh/Animiru/assets/53310735/c2cb667e-9e64-4f57-a4d2-b4e48c223244)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.0.0](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by quickdesh** [comment]
Fixed in new update
