### ISSUE TITLE
HDfilmcehennemi: Rapid player does not work in the app.

### ISSUE THREAD

**Issue by ghost** [Quickdesh/Animiru#81]
### Steps to reproduce

1.Open Animiru
2. Open the movie you want to watch on the HDfilmcehennemi source

### Expected behavior

All available players from the source must be in the app.

### Actual behavior

But whereas the source has the rapid and vidmoly player, Animiru only shows the vidmoly player.

### Animiru version

0.16.0.0

### Android version

Android 10

### Device

Pixel 2

### Other details

In the vidmoly player we could select the Rapid player for some movies and TV series when the image quality was not good, but in the app only the vidmoly player is available, even though the source itself has the rapid player.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.0.0](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by lasersPew** [comment]
> If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).

Hmm...
