### ISSUE TITLE
[Suggestion] App navigation bar improvements

### ISSUE THREAD

**Issue by mostidaniel** [Quickdesh/Animiru#83]
### Describe your suggested feature

Hi! I only recently used the app. Really loved it so far. However, I find some minor inconveniences with the navigation while using the app. First of all, I think that the bottom app navigation bar is too "short" or small. My thumb is literally wider than the app navbar buttons. I think that this should be fixed so that the usability and accessibility of the app can be improved further. Here are some suggestions to improve the app navbar:

### App NavBar + Labels
I think that simply bringing back the ability to show labels on the navbar is a game changer.
- First of all, it will add more space and padding for the button and navbar overall. This would greatly help with using the app navbar.
- Next, it will also be a handy accessibility feature since some people simply cannot see the icon and rely on screen readers to read the navigation bar.
- So I think having a label would greatly help. At the very least, it should be an option you can turn on or off.

### Add padding to app navbar buttons
This is probably the easiest fix, since it only involves adding padding to the navbar, but I am not an android developer so I can't really tell how hard to do it.
- I think that this would mitigate some minor issues I've personally had with the bottom navigation bar.
- But I also think that this won't resolve the accessibility issues with the current bar.
- Personally, I don't mind just having this be implemented because it will improve my experience with the app navigation nonetheless.

### Improve swipe gestures
The swipe gestures available on the app navbar is really great, but I think it can be better.
- When the current selected "page" is at the start, you cannot swipe it directly to the last page.
- For example, if you are at the "Library" page, you cannot swipe left to go to the "misc" page.
- I think that adding an ability to "roll over" the swipe could improve usability, but on the other hand, I think that it could also hamper accessibility, although I don't know who would use the swipe gesture if they are having trouble seeing the screen anyway.

I hope that you would consider adding any of these suggestions, but I'll still be using the app even without these features implemented. Thank you and I hope you have a great day.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0.0](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by quickdesh** [comment]
Have increased the height to match the standard used in other apps
