### ISSUE TITLE
Animiru as a media player

### ISSUE THREAD

**Issue by khaled-0** [Quickdesh/Animiru#90]
### Describe your suggested feature

How about Being able to open external media with animiru's player.
From an external file manager.

It would also be nice to be able to show a media notification in that case

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0.0](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by quickdesh** [comment]
https://github.com/abdallahmehiz/mpvKt

The media player based on the current player, but much better.
It is what the updated internal player will be based on moving forward.

**Comment by khaled-0** [comment]
> https://github.com/abdallahmehiz/mpvKt
> 
> The media player based on the current player, but much better. It is what the updated internal player will be based on moving forward.

yeah. also the official mpv android is being ported to material 3 by me

**Comment by quickdesh** [comment]
eyyy, Noice!
