### ISSUE TITLE
Cannot be installed in android 7.1.2

### ISSUE THREAD

**Issue by lasersPew** [Quickdesh/Animiru#94]
### Steps to reproduce

1. Download app from releases
2. Try to install ir

### Expected behavior

Installs normally

### Actual behavior

It doesn't install, at all

### Animiru version

0.17.1.0

### Android version

Android 7.1.2

### Device

Samsung Tab 3 Lite(T113NU)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.2.0](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
android 6 & 7 support is no longer available on latest versions. there is exclusive release for it usually named 0.16.xx

current latest exclusive android 6&7 release is this one: https://github.com/quickdesh/Animiru/releases/tag/v0.16.2.0

note that it's an upstream change so there's nothing they can do about it.
