### ISSUE TITLE
Episode Download Issue 

### ISSUE THREAD

**Issue by RafedAlMahmud** [Quickdesh/Animiru#97]
### Steps to reproduce

1. Open "The Eminence in Shadow 1st season" 
2. Try to download episode 1
3. It shows 0 MB (on the outside) & can't recognise file format while try to play it offline.
![Screenshot_2024-08-13-15-45-32](https://github.com/user-attachments/assets/c633cdcb-ea5f-4bda-8936-9e574a96c677)
![Screenshot_2024-08-13-15-45-53](https://github.com/user-attachments/assets/90e1a70c-45f3-446d-88ac-1c434d7664e6)
![Screenshot_2024-08-13-15-47-14](https://github.com/user-attachments/assets/d0f96bcd-f41d-4ef2-a277-97c773bc94f0)

### Expected behavior

"Should play the episode"

### Actual behavior

"It shows 0 MB (on the outside) & can't recognise file format while try to play it offline."

### Animiru version

"0.16.2.0"

### Android version

Android 6

### Device

Huawei CRO-U00

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [ ] I have updated the app to version **[0.17.2.0](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by khaled-0** [comment]
It's an issue with ur extension,
They're getting broken with time.
Look for a maintained one
