### ISSUE TITLE
No Update For About 2 Months Is The App Going To Be Shut Down By DMCA Or Operation Anime Or No

### ISSUE THREAD

**Issue by 9SYorhaDestroyer** [Quickdesh/Animiru#98]
### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Crash logs

N/A

### Animiru version

0.17.2.0

### Android version

Android 14

### Device

Samsung Galaxy A15 5G

### Other details

Please update the app and inform us if dmca is going to shut you down or operation anime

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official anime extension, I should be opening an issue in the [extensions repository](https://github.com/aniyomiorg/aniyomi-extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://aniyomi.org/docs/faq/general) and [troubleshooting guide](https://aniyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.2.0](https://github.com/Quickdesh/Animiru/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by fakebhai** [comment]
no, usually it's merged from upstream when it's stable or enough changes are made and sometimes it's easier to just remove "manga side" and apply additional changes. so as long as upstream is there animiru should be fine.

**Comment by cybergazer** [comment]
Aniyomi itself hasn't been updated in 2 months. All the forks are being unmaintained sadly

**Comment by fakebhai** [comment]
> Aniyomi itself hasn't been updated in 2 months. 

aniyomi's being maintained and latest beta/preview release itself was 40~ days ago. if you wanna update even further then build it yourself.

>All the forks are being unmaintained sadly 

only offical fork which's gonna get maintained is animiru as Kuukiyomi decided to discontinue.

**Comment by quickdesh** [comment]
As mentioned above, the project is still active. I just took a break for a while
